### ISSUE TITLE
Stack Terraform Fails - "Out of host capacity"

### ISSUE THREAD

**Issue by aumouth** [MallocArray/Unifi-OracleCloud#1]
[ocid1.ormjob.oc1.ap-sydney-1.aaaaaaaablapgn3p2u65ho2u7xqae6bdmv7e6uito7r75ztljnaqgbuhwqlq.log](https://github.com/MallocArray/Unifi-OracleCloud/files/3741635/ocid1.ormjob.oc1.ap-sydney-1.aaaaaaaablapgn3p2u65ho2u7xqae6bdmv7e6uito7r75ztljnaqgbuhwqlq.log)

**Comment by MallocArray** [comment]
There was a similar comment on the Oracle forums recently about the same error and the recommendation was to try again later as resources are always being provisioned by Oracle to various regions.:
https://cloudcustomerconnect.oracle.com/posts/657117a494
https://cloudcustomerconnect.oracle.com/posts/e572c64397

It appears that Sydney only has a single Availability Domain, but for regions that may have more than one, try manually creating an Instance just enough to see which AD is listed as Always Free Eligible.  Currently the only AD in Sydney does not have this tag, and is most likely what is causing it.

**Comment by MallocArray** [comment]
Updated README with information about Out of host capacity error.
