### ISSUE TITLE
Unable to apply Terraform Actions for US East Ashburn

### ISSUE THREAD

**Issue by austinbarberrepo** [MallocArray/Unifi-OracleCloud#2]
I’m currently trying to use the USE EAST Ashburn region. I’m getting this error when trying to apply the Terraform Actions. - Error: Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found. http status code: 404. Any idea on how to fix it? I’ve tried deleting the stack and recreating it a couple of times. I’ve also tried different operating systems for the always free.

Thank you for your assistance!

**Comment by MallocArray** [comment]
Try going to Menu>Compute>Instances>Create Instance and click on the link "Show Shape, Network and Storage Options". Take note of which Availability Domain is tagged as "Always Free Eligible". Whatever number that is, enter it into the Variables section of the Stack so it creates it the proper Availability Domain. If none of them show as "Always Free Eligible" then Oracle may not have additional capacity for more Always Free instances at this time.

**Comment by austinbarberrepo** [comment]
Thank you for the extra tip! I had to go in and change my domain availability to 3.

**Comment by MallocArray** [comment]
Updated README with instructions for finding the necessary Availability Domain number
