### ISSUE TITLE
What is the username & password ?

### ISSUE THREAD

**Issue by kbp0930** [MallocArray/Unifi-OracleCloud#3]
Thank you for your script, I could make a unifi controller on OCI for free.
It works very well.
But, when I connect SSH to the instance, it ask username & password.
I use ssh_public_key following your instructions.
What is the default username & password?

**Comment by MallocArray** [comment]
Check the section of the README.md file for links to the Oracle page for "Instance Console Connections" and check the heading for connecting to the serial console under Windows or MacOS.  The instructions appear to be different from what I remember when originally setting it up, but in my Putty settings, I provide the private key file and connect to the hostname
ubuntu@<IP-Address-Here>

No password needed, but I think having ubuntu@ was key to getting it going originally.  The string mentioned in the Oracle article may be more straight forward.
