### ISSUE TITLE
Stack failing to deploy using Ampere Shape

### ISSUE THREAD

**Issue by ga2pegw** [MallocArray/Unifi-OracleCloud#4]
Hi,

I followed the steps and was running my controller with the standard E2 micro instance for months, but wanted to try to redeploy using the Ampere shape, and I get the below error when applying the stack. Is there any fix for this by any chance?

Warning: Interpolation-only expressions are deprecated
  on main.tf line 6, in resource "oci_identity_compartment" "unificontroller_compartment" 
   6:     compartment_id = "${var.compartment_ocid}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
(and 32 more similar warnings elsewhere)
Error: Invalid index
  on main.tf line 24, in resource "oci_core_instance" "unificontroller-instance" 
  24:     source_id   = "${lookup(data.oci_core_images.supported_shape_images.images[0], ""id"")}"
    |----------------
    | data.oci_core_images.supported_shape_images.images is empty list of object
The given key does not identify an element in this collection value.

**Comment by MallocArray** [comment]
I've actually been playing with updating this so it could deploy an Ampere machine.  I think I just updated it to 0.12 or higher instead of my original comment of needing to stick with 0.11
I just changed to a new computer so I have to reconfigure my Terraform environment, so may not get to it for a few days, but I want to get it working.

**Comment by ga2pegw** [comment]
Ok no problem...if I can help out let me know (although I'm not great with
Terraform and the like...reason why I'm using this in the first place lol).
Appreciate the work!

**Comment by MallocArray** [comment]
Try the latest .zip file in the repo along with the updated instructions in README.md

I have it deployed in my instance successfully with 2 CPU and 6 GB RAM

**Comment by ga2pegw** [comment]
> Try the latest .zip file in the repo along with the updated instructions in README.md
> 
> I have it deployed in my instance successfully with 2 CPU and 6 GB RAM

Just deployed it with the latest ZIP and yes, it's working for me as well. Thanks for your quick turnaround on this!
