### ISSUE TITLE
Not getting an SSL Cert

### ISSUE THREAD

**Issue by petrus9** [MallocArray/Unifi-OracleCloud#5]
Hello Thanks for this great stack!  
I am not getting an SSL cert for my fqdn when I install this and think it is supposed to install that automatically?
The problem though is that the ip address is assigned before I can add it to my dns.

 I tried putting an update URL in the DDNS variable   (Mine is for Google Domains)  to update a dynamic dns record, but this did not work. 

Any ideas about how to get the cert to deploy during the stack build?

**Comment by MallocArray** [comment]
Similar to https://github.com/MallocArray/Unifi-OracleCloud/issues/6 I used a script from another Ubnt forum member to add that support and haven't fully tested it.  Could be a difference between Debian that he built it around or just recent versions of Ubuntu.

I'll have to take another look at his script to see if he made any recent changes and how it can be adapted for Oracle and Ubuntu 20.04

https://metis.fi/en/2018/02/gcp-unifi-code/

**Comment by MallocArray** [comment]
This is supported now, as the Easy Install Script that is called fully supports Lets Encrypt
