### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by alegazz** [MallocArray/Unifi-OracleCloud#9]
Hello
thank you for the guide, great job!
now I have to connect to the server console with "cloud shell connection" but I havn't username and password
I think username is ubuntu but password?
Thanks!!

**Comment by MallocArray** [comment]
The only way to access it is with an SSH key that you can provide when the VM is created in the stack.
https://github.com/MallocArray/Unifi-OracleCloud#ssh-access-to-instance

There are options in the web interface to add an SSH public key to an existing instance, but I have not been able to get it to work.  So I make sure to add the public key to the Stack variables and Apply, which may need to recreate your Instance.

**Comment by alegazz** [comment]
i destroyed the stack and recreated with the ssh public key and now it works.
I also tried to insert the public key to the existing instance but it didn't work at all.
I needed access to the server to update the unifi controller.
Thank you very much!
